### ISSUE TITLE
[Feature Request] Hoe radius enchantment

### ISSUE THREAD

**Issue by Disketaa** [Now-this-is-crazy/FarmTweaks#1]
An enchantment that will expand hoe right click crop action in a radius like:

1 block -> 4(2x2) blocks or 5 blocks (plus shape) -> 9(3x3) blocks

**Comment by Powercyphe** [comment]
I see the appeal but unsure if I wanna implement it into this mod as its mainly there to add just some qol features to farming, not anything major like enchantments

**Comment by Powercyphe** [comment]
Heya, I added a config option for this in the latest version

https://modrinth.com/mod/farmtweaks/version/1.9
