### ISSUE TITLE
[Help Wanted] Is there a way to change what crops can be right-clicked? 

### ISSUE THREAD

**Issue by Disketaa** [Now-this-is-crazy/FarmTweaks#3]
For now, I can't fast-harvest Nether Warts. Can I edit this somehow? Or it is on your side?

**Comment by Powercyphe** [comment]
You should be able to edit it in the config.

**Comment by Disketaa** [comment]
![image](https://github.com/user-attachments/assets/ee88145e-4b94-4326-9680-2019be693060)
Where?

**Comment by Disketaa** [comment]
Also I add new values into dispensableItems group, but the items are not planting anyways
![image](https://github.com/user-attachments/assets/ad8bc0cc-4cf8-4372-b1c0-86a4b18ed08e)
![image](https://github.com/user-attachments/assets/68cbd427-3381-44e4-9cf9-9533fe12c8cf)

**Comment by Powercyphe** [comment]
Odd, I'll see if I can get a fix out for that soon

**Comment by Powercyphe** [comment]
Update: Got an update in the works that will fix this issue

**Comment by Powercyphe** [comment]
Alright added a config option aswell for harvestable crops in the upcoming patch
